version: '3'
services:
  sftp:
      build: .
      volumes:
        - sftp:/home
      ports:
          - "2222:22"
      command: 
      - 'foo:pass:1001'
      - 'bar:pass:1002'


volumes:
  sftp: 